Repository jinsujini/SSWU_SONSAEKIM, pull requests merged in 2025-06, with the labels that each got.

#60 [FEAT] 이미지 연결
  controllers/quizController.js
  models/quiz/quiz.js
  models/quiz/signWord.js
  public/css/quiz/quiz.css
  public/js/quiz/renderQuiz.js
  views/quiz/quizPage.ejs
Labels: ✨Feature

#61 [FEAT] 배포용 바인드 범위 수정
  app.js
Labels: ⚙️Setting

#64 #54 [FEAT] : 카운트다운 추가
  controllers/learnController.js
  public/css/imitate/imitate.css
  public/css/learn/learnSelect.css
  public/js/imitate/camera.js
  views/imitate/vowel.ejs
Labels: ✨Feature, :hamster: 예은

#66 [Feat/#43] 오답 모아보기
  controllers/learnController.js
  controllers/quizController.js
  models/quiz/vcWrong.js
  models/quiz/wordWrong.js
  public/js/quiz/renderQuiz.js
  public/js/quiz/renderQuizWrong.js
  routers/quizRouter.js
  views/quiz/noQuiz.ejs
  views/quiz/quizMenu.ejs
  views/quiz/quizResult.ejs
  views/quiz/quizWrong.ejs
Labels: ✨Feature, :black_cat: 민선

#67 [Feat/#25] 북마크 기존 상태 반영
  controllers/quizController.js
  models/index.js
  models/quiz/bookmarkVc.js
  public/js/quiz/bookmark.js
  public/js/quiz/renderQuiz.js
  public/js/quiz/renderQuizWrong.js
  routers/quizRouter.js
  views/quiz/quizPage.ejs
  views/quiz/quizWrong.ejs
Labels: ✨Feature, :black_cat: 민선

#69 [FEAT] : 따라하기 오답 결과
  controllers/imitateController.js
  public/js/imitate/renderImitate.js
  public/js/imitate/renderImitateWrong.js
  routers/imitateRouter.js
  views/imitate/imitateResult.ejs
  views/imitate/imitateWrong.ejs
Labels: ✨Feature, :hamster: 예은

#72 [Fix/#43] 오답 인덱싱 수정
  controllers/quizController.js
  models/quiz/bookmarkVc.js
  models/quiz/bookmarkWord.js
  models/quiz/signVc.js
  models/quiz/signWord.js
  public/js/quiz/renderQuiz.js
  public/js/quiz/renderQuizWrong.js
Labels: 🛠️Debug, :black_cat: 민선

#73 [#25/FIX] 북마크 오류 수정
  controllers/quizController.js
  models/quiz/bookmarkVc.js
  models/quiz/bookmarkWord.js
Labels: 🛠️Debug, :black_cat: 민선

#80 [FEAT/#79 ] 게임 서비스계층 분리, 헤더 연결
  configs/config.js
  controllers/gameController.js
  routers/gameRouter.js
  services/gameService.js
  views/layouts/header.ejs
Labels: :anger: FIX

#88 [FEAT/#65 #77] 따라하기 결과 & 넘버링
  controllers/imitateController.js
  public/js/imitate/renderImitate.js
  public/js/imitate/renderImitateWrong.js
  public/js/imitate/start.js
  routers/imitateRouter.js
  views/imitate/imitatePage.ejs
  views/imitate/imitateResult.ejs
  views/imitate/imitateWrong.ejs
Labels: ✨Feature, :hamster: 예은

#92 [Feat/#58] 모음, 단어 데이터 추가
  public/assets/sign_vc/수어_ㄱ.png
  public/assets/sign_vc/수어_ㄴ.png
  public/assets/sign_vc/수어_ㄷ.png
  public/assets/sign_vc/수어_ㄹ.png
  public/assets/sign_vc/수어_ㅁ.png
  public/assets/sign_vc/수어_ㅂ.png
  public/assets/sign_vc/수어_ㅅ.png
  public/assets/sign_vc/수어_ㅇ.png
  public/assets/sign_vc/수어_ㅈ.png
  public/assets/sign_vc/수어_ㅊ.png
  public/assets/sign_vc/수어_ㅋ.png
  public/assets/sign_vc/수어_ㅌ.png
  public/assets/sign_vc/수어_ㅍ.png
  public/assets/sign_vc/수어_ㅎ.png
  public/assets/sign_vc/수어_ㅏ.png
  public/assets/sign_vc/수어_ㅐ.png
  public/assets/sign_vc/수어_ㅑ.png
  public/assets/sign_vc/수어_ㅒ.png
  public/assets/sign_vc/수어_ㅓ.png
  public/assets/sign_vc/수어_ㅔ.png
  public/assets/sign_vc/수어_ㅕ.png
  public/assets/sign_vc/수어_ㅖ.png
  public/assets/sign_vc/수어_ㅗ.png
  public/assets/sign_vc/수어_ㅚ.png
  public/assets/sign_vc/수어_ㅛ.png
  public/assets/sign_vc/수어_ㅜ.png
  public/assets/sign_vc/수어_ㅟ.png
  public/assets/sign_vc/수어_ㅠ.png
  public/assets/sign_vc/수어_ㅡ.png
  public/assets/sign_vc/수어_ㅢ.png
  public/assets/sign_vc/수어_ㅣ.png
  public/assets/sign_word/개.jpg
  public/assets/sign_word/걷어차다.png
  public/assets/sign_word/고양이.jpg
  public/assets/sign_word/국수, 면.jpg
  public/assets/sign_word/낙지.jpg
  public/assets/sign_word/드레스.jpg
  public/assets/sign_word/떡.jpg
  public/assets/sign_word/만화.jpg
  public/assets/sign_word/맥주.jpg
  public/assets/sign_word/무지개.jpg
  public/assets/sign_word/미소.jpg
  public/assets/sign_word/미안하다, 죄송하다.jpg
  public/assets/sign_word/벼락.jpg
  public/assets/sign_word/별.jpg
  public/assets/sign_word/빵.jpg
  public/assets/sign_word/산.jpg
  public/assets/sign_word/어지럽다.jpg
  public/assets/sign_word/엿.jpg
  public/assets/sign_word/온도.jpg
  public/assets/sign_word/칫솔.jpg
Labels: ✨Feature, :black_cat: 민선

#93 [Fix/#90] 북마크 연결 오류 수정
  controllers/quizController.js
  public/js/imitate/renderImitate.js
  public/js/imitate/renderImitateWrong.js
  services/quizService.js
Labels: :black_cat: 민선, :anger: FIX

#95 [CHORE/#94] authService 대소문자 수정
  services/authService.js
Labels: :panda_face: 시현, CHORE

#116 [Fix/#43] 퀴즈 오답 방식 수정
  controllers/quizController.js
  models/quiz/vcWrong.js
  models/quiz/wordWrong.js
  public/js/quiz/quizResult.js
  public/js/quiz/renderQuiz.js
  services/quizService.js
  views/quiz/quizMenu.ejs
  views/quiz/quizPage.ejs
  views/quiz/quizResult.ejs
Labels: :black_cat: 민선, :anger: FIX
